### ISSUE TITLE
Should include LICENSE header comments

### ISSUE THREAD

**Issue by euank** [Mechazawa/rms.sexy#7]
Richard Stallman himself has warned of the dangers of executing closed-source javascript.

While this repository does include a "license" (dedication to public domain, whatever), there is no copyright notice included in the html, css, or javascript of the webpage.

This could lead users of the webpage to not realize their rights.

Secondly, I think you'll find that this page would best be distributed under the AGPL. I believe that there are few enough contributors that relicensing should be possible.
We have been warned of the dangers of proprietary SaaSS offerings, and I would hate to think that due to a non-copyleft license, this service might one day be hosted by a SaaSS company like Amazon to the user's detriment.

If you wish to keep it public domain, the fsf [recommends CC0 instead](https://www.gnu.org/licenses/license-list.en.html#Unlicense) btw.

**Comment by Mechazawa** [comment]
So add license headers and relicense to AGPL? 
@clsr Is that fine with you?

**Comment by clsr** [comment]
It's public domain, you don't actually have to ask me to relicense.

While I generally disagree with the way AGPL works (software licenses 
should put restrictions on developers, not users), I do understand the 
problem it tries to solve. Feel free to relicense my contributions to 
AGPL.

**Comment by euank** [comment]
You actually bring up a good point though @clsr; since it's already public domain, I don't think it's possible to put it back under copyright (or, in this case, copyleft).
The cat's already out of the bag so to speak.

It seems like the only way this project can fully preserve user's essential rights is through a full, properly licensed, reimplementation.

For now, I'll make a PR which includes suitable header-comments so users know it's public domain...
but I think the only way to fully preserve user's rights would be a reimplementation that's licensed correctly from the get-go.

**Comment by clsr** [comment]
It certainly is possible to relicense it. The current version of the 
code will remain available in the public domain, but any future updates 
would be licensed under the new and more restrictive license.
