### ISSUE TITLE
The sexiest .sexy domain is down

### ISSUE THREAD

**Issue by SharkWipf** [Mechazawa/rms.sexy#9]
I felt a great need to watch the sexiest holiday pictures today but, much to my dismay, it seems rms.sexy is down.  
Whois data says `Domain Status: clientHold https://icann.org/epp#clientHold`.

**Comment by Mechazawa** [comment]
The domain was costing me 44 eur a year and I sadly do not have money to blow on a site like this right now. The domain should be up for grabs soon.

**Comment by fronbasal** [comment]
Aw shit :(

**Comment by z** [comment]
The Internet needs this resource to exist!  Maybe you can setup a gofundme or a bitcoin address?

**Comment by euank** [comment]
I've offered to run rms.sexy and foot the bill. Assuming everything works out there it should be back soon! If you have spare money to donate, I believe the Free Software Foundation would be happy to have more members :smiley:

**Comment by fronbasal** [comment]
Yay!

**Comment by Mechazawa** [comment]
I've transfered the domain to @euank and I'll transfer the repository once he's deleted or renamed his fork.

**Comment by euank** [comment]
It should be back up (technically for the last day or so), and also now in its new home, so this can be closed!
:tada:

**Comment by Mechazawa** [comment]
Repository is currently being transferred and after that @euank is the new home of rms.sexy!

**Comment by z** [comment]
Yay, this is why I love the free software community!  Great job guys, really nice turn-around time on a solution.  Our children will appreciate this.
